#!/usr/bin/env php
<?php
mb_internal_encoding('UTF-8');

require __DIR__ . '/vendor/autoload.php';

use Momo\Redmine\Console\Application;
use Symfony\Component\Dotenv\Dotenv;

if (is_file(__DIR__ . '/.env')) {
    $dotenv = new Dotenv();
    $dotenv->load(__DIR__ . '/.env');
}

$application = new Application();
$application->setConfigYamlPath(__DIR__ . '/config.yml');
$application->run();
